name: example
dependencies:
  hive: any
dev_dependencies:
  build_runner: any
  hive_generator_plus:
    path: ..
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependency_overrides:
  hive:
    path: ../../hive
  hive_generator_plus:
    path: ..