name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.0.0
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  hive: ^2.2.3
  analyzer: ^6.0.0
  source_helper: ^1.3.4

dev_dependencies:
  test: ^1.24.5
  build_test: ^2.2.0
  build_runner: ^2.4.6
  pedantic: ^1.11.1
